<?php //006f2
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Bestellmengenmanager @version 5.0.4.1 PHP71 (01.12.2020) @author  Daniel Stein support@shopmodule.com @copyright (C) 2020, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPqxXGhHwIRUx0rNNbn3o+NtRqqlOU0IotlfnBDW0eQPV2OCld7pMnY2jNoTw7DSVchdbjbsA
9IbPnq0fW9rsUHYcWUVuvQSXJw1s61qKyqUso9Xf/T7fSE6bqD66CaUTOhMDoq3aIynlAjWVnWwB
hwr79Cjxxl35O6eSykRlZRHbZ0BnnkZhOJgP5+E2HdLiszNmSoEsmcVvcTjq0q9/+JYxVYrvTa3s
0EWv2XqzcO7IHCuHPRfldDbhizz0tdZVtDFyXVRgRPTY8sN4uYIM8mI9c1E0SALOhx/ErFtPy5qC
r9x5UKMq00PQWt2mUPz44CxjPvm8yhW9m71EJrq7FlkCFJBzA533FgtJ8n7cOSLNz+TwqcbfLigk
n4gwk9icG4+YRSewaD90lNoPuN95RtXkEFQ9/8aDzK6NrvZOLhXV9BxXt/aZrDhTc4oqjceYuWp3
XaKPbUaujyv/owCb0dNTudf11ZdYoVygyu1rIJJ/4gbhfxTAku0=