<?php //006f7
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Bestellmengenmanager @version 5.0.4.3 PHPcust (12.10.2021) @author  Markus Gärtner support@shopmodule.com @copyright (C) 2021, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cP+4gjtQPz0jvP9aYLP0QW8HthOOHuTzViz+OUGIfPCbHc/AvykjMPELfUsz1YqKlx3N0gI3X
34SdXp0g41U5G8zQMr18HUb/4mHKd1kvpSRytJ8AhMrdNZLURHSPTrAJGFVVRMrETu4YOJSSB6jj
N9rrQMZ8eihEWrNeMjQUtiFEQWua5p1NdsPiSY98jiqiXT8VZz+1afmEguUIk+tMMBsPnI9MrlYC
WyNbyr7JBghNYhQw7ti2n9Vwj65l/LFPAjlF+tfFaz2UGmh6ygd5TIbggYNSQQaesYWV084VlVab
p3BcL1dmAUiBI2DnFIFlwEg+zwg+aL+f7uoq/9hrb7ydvSMIuA7YRNfgbIVYdNa5mL3J1zh8SO1a
hQ4Sfayibr96QSXEbsUaaReEIc2kulPsKVpOkWcl0Fhf6qeRDJQ6Ux0anQtGQjiwDVEIAp3DGy5t
CqSTzRBbChfFHAvF+TilHJJEhcJNqy4BKbFoJsJgBThfRB7rsc30HfeFNd1mQU7mItZxFsQtZJaP
N/UDKiIwOEqvlXM4x41Z7bTA75JgzuSkxBDLEoUyFbJ2RkQU9GeodP3ExV4B6ZwcKd5XhqLXv4O6
FeB2CethvQGrqOT9ZeIGSro2KStM6CZMb+QW/somM+KuMEbPKqPIqnI7UT3271rThVBlB1JtzSM9
mw4RPjCFEdlUu0jKW2e/ugXChduMUru7s12p1w88dSJvdVYszJyGn8PVWAk5e8VUa6VtOu8jIsWe
rL//uMNvcIi45BSaRqRuOgt/HUYrXbFUqe9WXiukX18RbfIzd/KSq8CbxGzBq9NCNkHmCKTY5s+w
rVx/X56/sF3YO+J7Ivo+JgwrheE+Qp4AkDrOGqH9KM7sbrBmEKFoRi/EgEMKqi2SlOBNQV2Un+Oi
iLv1S+8ZIsgWf6VypLaQoqeIzSDpO8qKagtpwoML63DM3Wna49o1Emu6YExkfFYvu2kejbc6Xn8T
3yy9DF/6qXCn1vX4jpJ+DkAqJ+R5AGYZubmo1KWcCQWcMeJf0HhATsZBWaZaoVBn7sBZyMdxSs+i
N/GrvtjOffhZ1jTmCvP+f+S/AfphUwX70398vsCoTZ64R0AEiOEAk9RrJ2pzxsL2N/AovgJvI1/p
4sbVvpWwfGvQBSVaEFPqma5u1xE8U78JaN+GTFg08/GplLwtu0vALKeWEE6RgdWq8zLQjYp0+8aY
ip7VEqhL9tsSLH4E4B/bTlf5bhKwCAS2TBmLz3a3oVGbjOE50bYwdaQSfN1SIMpZCXfa98YIwqy1
IeNEWxf9y7MLnqOLGWZn/jkTs0kcol0OIjQTOJN2yCmbV9ru8hNc1n2KEaZ/chc2iHzyEwCRaaRW
NQYCfdkfslQ/SRqAZ/GIM00nJZbENsFjpw6C02mu5ZvSehUhub+kgNDApmQKLFUdc+0MwdfkQGt6
tTmfDUyfMMYZtV+mizG+j3vhPl0D6WbmLDKUKD2RjWg5/f8C/H+lWObLwlqe6Fk8hua+tdpm/eWX
19pP0ILZa6xFIpDBzejfbHAXviE38Z9IM8Fna/ADqMCdUNUgHmRHQ7Hi6TPkGoTDD/ErD5UnI+qd
Q4wzs/zUvnluqUhuIe79U/WFZXoNlh7u+58TghE8PdQqWJ7Vw9yQfHJ1ONiZgIyI1ZWw1xnmmCtB
wrUgiLK+CN0eg3VFOzNO9/+FtHkFfltsejZTER7H9L8INeFMqI4xHI0As2U5r+Tdqvi9gYpE2mbR
6kaHJiyjwnJY13lrR+AmWooai+army7+X1GeGtFs0EUBQzlpT1niG+d2VMCgfrP8cvScj3Jpl7ut
xAD8zcdV894KVSRDgh2T2TDHkWexzkn01QdUX0DanmvfqRf1hQ8SkWrYQ+l+6VbDlalirNz0rAEc
b08LATw0cYlCIaKGOlfq2nMlrc6hTfA3IxPaVAlQi+DNGn0qkLyZK01eY/EMkUukinCVDMajaSxt
r2FiVwMNt8vvNZUHhw+76TzvDcmgeQoBzhhqnh447rMZ82qRMzagqSAcjj9UXCIkBbFzJR5JR5Nl
4kednwAvxAfz3PLkhLhIpr+s3+trYAXKBrUeQXEFnMpF4/fP+xa6be8tUyUwOD1P7bk++ijqVGrB
rMF2CbQJifalxm8t4dcQXHRCW3eryyfyijOYjCCuhivPEdpy1XmWvbV5CxqL0t4VsiQNc4zLhbrM
adZ6yV3yR9w4Hq7fAEy7D2p6zSbrgm5arj8WjvuSRHYzmdJnqbF2MQmBxtbnUMNzo+No/Qu6q0lQ
FIqX7U44XRvX074nCFf4QhM5AeTFO3ZOAFLkuMbWPtjcjMysvlfmRtK4HB8j2ZfiwsqAMOGbETHZ
UN56X5I0PjC+VR2GT8jqzzvHYTu731mEZYP0bXem7Md0g9rkg0YSlHmrY3Et9VWqOguNX2TTDWok
umH+ZX531LVSZlhA167gu4jzGDeaNJ0zEjwZTUniDExmb8mQ0mUS3Jzbo0iPwVo48t+VSwG44cpY
1U5qeaDkBZWRUXuQ0x60MN9O8ZbTJEpvlnAJr0ntVdomkWO6lOq042iSkMJfbGwCWvfXtv6LAoBl
0Lzh9hmWtNnuPpx0vDL8Dw47DSNkISlGELorK/AVVWaxahGXQFBunSsaAjHYGavAlm7sDC5TRt+5
UBHId2IfT24I5uo5ctzHdzWrHOPPzaoi1k++2MUDBm9tNs29UsiDXB/p/AlqB0lHlVyGNuii5Ghx
abHkZs6wvPT/P2iJZPV7+ZEmpVC5v5YK1aE+G/EtyoNcOHv/M/DawiHHb6VbPX/4oyJKvr9neI6g
uZG=