<?php //006f4
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Bestellmengenmanager @version 5.0.3.0 PHP71 (08.05.2020) @author  Daniel Seifert support@shopmodule.com @copyright (C) 2020, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPpK2UZjFw5uz5hRl656EzFRygIwy1UxSbDKS5V0Pb2Z6BsZqKR7jMcugUpLujOrqyTWk0s/w
2RQRSw4kcz+pEPsxLtkANqOgrDhgeP5rF+irXf7JG2Ec9aXJPPr6IVpbm2vg2JicWXPEWzUMtFpU
NRZHEbz7i0qQ0xfBRqX7Z2Ogzu6zsCybhe5EPVUnAzLHKrOCsQpcz0QJj40IraPDN23h4ls5/zbS
oiNucJGfMArCcb+dmiegOYbb4psMk+9AH/LWJR7ctG7tRHRZvYnc8Q7lqhykQcjSLTj9Zv2qdvU+
zqMXBNaEue9u7pjOqaCaGmZDSnFhceYh2txSQczA6SdSERl0DWAirTC7/cSHsQibEiYjQgt7alSh
LDETx7b6ZlUIe0FBlneYkxtU9hrxQFMCueMskg15tEXHgNDonrIlDfhnNZhzAtgVfK2KGpsBqG6u
t0nAbzgVfCPbqGWtZVCUUQk82Ts1gBoN2i6nBOXjReCl5xPEoe1Wg6nB52iCgQgdlVyrUNuE4bRm
5212Cn6rGjORbbmgkfVaVWaBdU4G9M1E9JT79Y+mrmtGX/pUIDgPq33KqNoKewwEYcsadrQFA6lX
r01ouzp4u3uCb4dqafIWKWEKQVOv7lMr07lRv0==